---
title: "为什么我更喜欢 NPV 而不是 IRR？"
author: "Maverick McQuillan"
date: "2025-12-20"
categories: [Finance,Math]
image: ""
draft: true
---

假设你现在需要 100000 元，但是手里没有钱，于是你想向他人借钱来应急，现在有两种方案供你选择：

- 立刻得到 10 万元，然后在接下来的 **30** 年内每个月还 **1028.61** 元。

- 立刻得到 10 万元，然后在接下来的 **15** 年内每个月还 **1100** 元。

无论是哪种选择，你都需要付出代价。那请问我们应该如何去衡量这个代价？

这个代价最好能统一度量衡。那么*最直观的想法就是我未来每个月付出的钱相当于我现在立刻付出多少钱？*如果 A 方案未来付出的代价转化成今天的直接金钱损失比 B 方案要小，那么我就选 A，反之依然。

那如何来衡量这个**当前的立刻损失**就牵涉到现值的概念，即为了达到未来还账的目标，我需要现在把多少钱投入收益率为折现率（discount rate）的银行中？ 

假设你知道一家银行的存款收益率为 12%，那么你就可以把钱分成 12 * 30 = 360 份，分别投入到360 个银行账户中（实际上一起放进到一个银行账户就行），每个银行账户分别对应着未来 360 个月的还款，即等到第 30 个月的时候用第三十个银行账户的存款（已经有 30次的利滚利）去支付，第 40 个月的时候用第四十个银行账户的存款去支付。

那么很显然，这 360 个月的还债数额是固定的，但是我们为还款而准备的 360 个银行账户的起始存款是不固定的，比如为了第一个月的还款1028.61元，你可以在第一个账户中放入 $\displaystyle \frac{1028.61}{1+1\%}=1018.43$ , 而为了第 360 个月还款同样的1028.61 元，你在第 360 个银行账户中只需要支付 $\displaystyle \frac{1028.61}{(1 + 1\% )^{360}}=28.61元$ ，把这 360 个账户的所有的初始投放金额加起来就是你为了还款而付出的**当前的代价**。

实际上上述我们描述的过程就是计算未来还款金额的**现值**。可见现值的意义就是计算为了未来还款，你现在需要在银行存多少钱？相反如果未来不是你还钱，而是给你钱，我们也可以用现值的方式来计算，未来给你的钱相当于现在立刻给你多少钱，当我们计算投资的收益时，我们可以用未来收获的钱的现值来跟你投资的金额进行比较，如果大，就投，如果小，就不投，而这两者之间的差值就是大名鼎鼎的**净现值(NPV)**。




可以讲，NPV 的意义是非常直接的，我们衡量自己投资或者借款是否合适本质上都是用 NPV 的概念来去思考。与此同时我们也有另外一个概念来去衡量投资和借款是否合适，它就是**内部收益率（Internal Rate of Return，简称IRR）**。那什么是 IRR 呢？

还是那我们上面的两个方案来考虑，对于借给你钱的人来讲，他们的损失都是“目前的 10 万元“，这相当于投资金额，而得到的回报分别是 $\colorbox{lightgray} { 30 * 12 * 1028.61 = 370299.6元}$ 和 $\colorbox{lightgray} {1000 * 12 * 15 = 180000元}$, 我们乍一看还是第一个方案有点**太赚了**,但是别忘了
第一个方案的持续时间是第二个方案的两倍，实际上如果我们执行第二个方案得到的金钱不仅仅局限于18 万，我们可以把这十八万放到银行当中吃利息，再持续到第一个方案投资结束，等到那时我们收获的资金一定会比十八万要多。

那么这个时候，我们就会产生疑问，当投资的持续时间不一样时，怎么确定两者的收益谁大谁小？当然最好还是直接去用 NPV，即将我们未来收获的金钱折算成现值与本金比较。使用 NPV 计算的前提是我们要有一个知道其固定利率的银行，那反过来我们也可以这样想象，即
项目投资未来收获的权益，相当于我把本金投入到什么样的利率的银行当中储蓄，才能得到同样的结果？而这个利率就是 IRR。

通过计算我们可以得到第一个方案的IRR（月利率）为 $\displaystyle 1\%$ 和 $\displaystyle 0.868\%$ , 即为了得到两个方案的未来现金流投资收入，我们可以分别把 10 万元投入到月利率为 $\displaystyle 1\%$ 和 $\displaystyle 0.868\%$
的银行账户中，然后就可以高枕无忧了，每个月拿规定的固定投资反馈金额，一直到投资阶段结束。

那如果我们投资时，现有的银行利率是 $\dislaystyle 2\%$ ，那么我们把十万块钱放到银行账户中，我们不仅可以每个月固定拿到以上两个项目投资所得的钱，投资期限结束后还有剩余，那么显然跟以上两个投资项目相比，我们应该把钱放到银行更合适。如果银行的存储利率是 $\displaystyle 0.9\%$ ，那么很显然
我们把钱投入的银行中的话，可以达到第二个投资项目的效果，但是达不到第一个投资项目的效果，综合考虑我们应该选择第一个投资项目。 

