---
title: "采访了十位大学校友后，我的感受"
author: "Maverick McQuillan"
date: "2025-03-12"
categories: ["人际关系", "大学"]
draft: true
---

最近这两天，我发表了与小 C 同学沟通的播客内容。除了第一期我跟我的大学好兄弟强哥一起做的之外，我已经跟十位在克拉玛依校区生活过的人进行了深入的交流。沟通完了之后，我其实感慨颇多，所以想写一篇文章来记录我现在的体会。

# 做播客的契机

在大三下学期和大四时期，我非常迷恋读书，当时去石油大学的图书馆借了好多书，也在网上去寻找有哪些优质的书籍推荐。偶然发现了一位非常有气质的北大毕业的UP 主叫做“是宇弦啊”，爱屋及乌，我也看了她跟她的北大室友“全嘻嘻”进行的宿舍访谈（当时她们距离宿舍视频被网暴还有一年多的时间），从中我了解了全嘻嘻，看了她很多的视频，可以说全嘻嘻这位 UP主对我的影响很大，她是一个很好的优质信息源，我通过她的介绍了解了很多东西，开拓了我的眼界。她和她的老公在B 站的一起视频中说她们非常喜欢听播客，并且推荐了一些她们认为高质量的播客节目和播客平台**小宇宙**。我尝试了一下，去小宇宙平台上听播客，感觉还是挺有意思，我第一次接触通过这种媒介来去传播信息。之前我也尝试过用做长视频和短视频的方式来表达自己，后来发现这样做风险比较大，因为每发一次视频，都像买一个文革批判彩票，如果你中奖了，那么将会迎接雷霆怒吼般得批判，鄙人曾经承受了两次，索性我及时退出，否则后果不堪设想，这也是我特别同情那些被孤立者的原因，我愿意在他们受难的时候，伸出援手。播客相对于视频来讲，受众人数没有那么多，尤其在中国确实还是方兴未艾，而且如果一个听众能把你长达一个多小时的内容听完，他绝对是你的灵魂粉丝，不会做断章取义的内容，而且播客的用户相对来讲确实比短视频的用户素质更高。所以我认为，通过播客来表达自己的想法是一个非常好的形式，每一个粉丝都深深认同你的观念和想法，你也可以免遭批判之苦。

在听取一些高质量的播客之后，我心里已经种出了想要自己开播客的种子。当时我跟我的大学室友（另外一个好兄弟）去北京的三里屯苹果 4s店去看苹果产品，其中有一个苹果的工作老师在台上讲演如何用库乐队去制作播客，我非常好奇，认真得边操作 IPad 边听老师说话，课讲完之后我还跟老师进行私下的互动。等到大学本科毕业的时候，我想趁此机会找一名同学谈谈读大学的感受，于是就找了我的好兄弟强哥，机缘巧合之下，在我离开石油大学的前两天的时候，我们俩在楼下的一楼录制了第一期内容。隔了好久，我在当年的 11 月份发表在小宇宙的平台上，当时感觉这个做播客还是比较有意义的事情，可能现在录制的音频听起来没啥劲，但是二三十年之后，你再听或者你的孩子去听当年父亲在大学时期的想法，应该会特别感激能有这么一段音频记录了这历史资料。

# 为什么选择校友访谈？

当时做完第一期播客之后，我还是想着未来播客发布的内容应该是围绕着我自己，发表自己的看法和感悟，但是后来想了想，播客的发展路径应该专业化，我打算主题应该围绕着克拉玛依校区，我于是先找了几个我在大学比较熟且见过面的人，请他们跟我在线上进行录制。做完几期之后，我认为更应该邀请一些我不是很熟，但是有自己在克校区独特经历和看法的人。当时播客的基础已经搭建起来，我也比较好邀请他们来一起制作。 制作的过程中，我最满意的就是我的配乐，这是一个创作的过程，也是一个体现个人品味的结果。我经常把我曾经特别喜欢的音乐和嘉宾的说话语调匹配，然后进行剪辑，最后做成了成品，我经常循环几十遍去听，有一次听得我耳朵都疼了。

# 访谈的感受
我目前只是采访了十位克拉玛依校区的校友（算上我自己），整体的样本数量并不多，所以得出来的结论和感受可能有失偏颇，甚至存在着非常大的偏见，请读者自己去独立思考我写作的内容。